name: MegaLinter

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions: read-all

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run Super-Linter
        uses: oxsecurity/megalinter@v8.5.0
        env:
          DEFAULT_BRANCH: staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
